### ISSUE TITLE
parse encoded space as plus sign

### ISSUE THREAD

**Issue by sharing-lab** [vladfaust/http-params-serializable#29]
many web browsers nowadays, encode space as plus sign.

```crystal
require "http-params-serializable"

class Params
  include HTTP::Params::Serializable
  property id : Int32
  property title : String
end

params = Params.from_query("id=42&title=my+title")
puts params.title  # my+title
```

output from the code above is : my+title
i think it should be : my title

Thanks in advance

**Comment by vladfaust** [comment]
> many web browsers nowadays, encode space as plus sign.

Please provide proofs to your arguments.
